project_id: "559843"
pull_request_title: "chore: new translations"
pull_request_labels:
  - translations
commit_message: "chore: new translations for %language%"
append_commit_message: false
files:
  - source: /src/locales/en.json
    translation: /src/locales/%two_letters_code%.json
