name: 'Release Beta Version'

on:
  workflow_dispatch:
  schedule:
    - cron: '42 22 * * *'

jobs:
  get-commit:
    name: Get commit message
    runs-on: ubuntu-latest
    outputs:
      msg: ${{ steps.set-msg.outputs.msg }}
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v3'
        with:
          persist-credentials: false
      - id: set-msg
        name: 'Set commit message variable'
        run: |
          msg=$(git --no-pager log -1 --pretty=format:"%s")
          echo "msg=${msg}" >> $GITHUB_OUTPUT
  bump-version:
    name: 'Bump version'
    needs: get-commit
    if: |
      !startsWith(needs.get-commit.outputs.msg, 'chore(release)') &&
      !startsWith(needs.get-commit.outputs.msg, 'ci: version bump')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v3'
        with:
          persist-credentials: false
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@v9.1.5'
        with:
          version-type: prerelease
          preid: 'beta'
          tag-prefix: 'v'
          skip-tag: 'true'
          bump-policy: 'last-commit'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      - name: 'Output new version'
        env:
          NEW_VERSION: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new version $NEW_VERSION"
    outputs:
      newTag: ${{ steps.version-bump.outputs.newTag }}

  draft-release:
    name: 'Draft release'
    runs-on: ubuntu-latest
    needs: bump-version
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Create draft release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ needs.bump-version.outputs.newTag }}
          tag: ${{ needs.bump-version.outputs.newTag }}
          commit: 'master'
          draft: true
          prerelease: true
          generateReleaseNotes: true
    outputs:
      id: ${{ steps.create_release.outputs.id }}

  build:
    needs: draft-release
    uses: ./.github/workflows/build.yml
    with:
      type: beta
    secrets: inherit

  publish-release:
    name: 'Publish release'
    runs-on: ubuntu-latest
    needs: [bump-version, build]
    steps:
      - uses: ncipollo/release-action@v1
        with:
          name: ${{ needs.bump-version.outputs.newTag }}
          tag: ${{ needs.bump-version.outputs.newTag }}
          draft: false
          prerelease: true
          allowUpdates: true
          omitBodyDuringUpdate: true
          updateOnlyUnreleased: true
          token: ${{ secrets.PERSONAL_TOKEN }}
