name: ci

on:
  workflow_dispatch:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master, refactor/next]
    paths:
      - 'electron-builder.json5'
      - 'package.json'
      - 'electron/**/*'
      - 'nuxt.config.ts'
      - 'yarn.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'yarn'

      - name: Install dependencies
        run: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 yarn install

      - name: Run linter
        run: yarn lint
      - name: Cancel workflow
        if: failure()
        uses: andymckay/cancel-action@0.3

  test:
    uses: ./.github/workflows/build.yml
    with:
      type: test
    secrets: inherit

  build:
    uses: ./.github/workflows/build.yml
    with:
      type: release
    secrets: inherit

  release:
    if: |
      github.event_name == 'push' &&
      !startsWith(github.ref, 'refs/tags/v') &&
      startsWith(github.event.head_commit.message, 'chore(release)')
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get version
        id: version
        uses: martinbeentjes/npm-get-version-action@v1.2.3
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ format('v{0}', steps.version.outputs.current-version) }}
          tag: ${{ format('v{0}', steps.version.outputs.current-version) }}
          draft: false
          allowUpdates: true
          omitBodyDuringUpdate: true
          skipIfReleaseExists: true
          updateOnlyUnreleased: true
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Delete older beta releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 0
          delete_tag_pattern: beta
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
